### PR TITLE
CASA GFED Carbon Flux - Initial updates for user data notebook

### PR DESCRIPTION
**Pull request by fb0023**
- [x] The first cell contains the rendering information with author and data
~~- [ ] The notebook has a **Run this Notebook** section (with filename in link)~~
- [x] The notebook has an **Approach** section
- [x] All the packages that are imported in the notebooks are used within the notebook
- [x] Dependency installs are in a non-executable cell (Markdown with a code block) as a single-line `%pip install abc def` statement
- [x] All imports are at the top of the notebook
- [x] Any complex geometries are accessed from remote storage
- [x] Each code cell comes after a markdown cell containing explantory text
- [x] All cells in the notebook book have been run in order with a fresh kernel (cell numbers should be 1, 2, 3, 4, ...)

### CODE REVIEW

**Review by j08lue — CHANGES_REQUESTED** [review]
@fb0023, please change pip installs and imports according to the new guidelines we are establishing:

- https://github.com/US-GHG-Center/ghgc-docs/issues/56

**Review by j08lue — CHANGES_REQUESTED** [review]
Please change the pip installs as in the example here: https://github.com/US-GHG-Center/ghgc-docs/blob/cd797b9bf7b5bc67fd27b0642997153f9ac93efb/user_data_notebooks/oco2-mip-co2budget-yeargrid-v1_User_Notebook.ipynb

image

i.e. all in a single line (no need to explain what every library does) and as code in a Markdown cell.

The explainers with the import statements are nice, but these comments should rather go where the module/function is actually used, or be removed, please.

Finally, you should run the entire notebook with a fresh kernel, please, so the cells are numbered. 

The checklist from veda-docs applies: https://github.com/NASA-IMPACT/veda-docs/blob/main/.github/pull_request_template.md

**Review by j08lue — CHANGES_REQUESTED** [review]
Great, just missing that you run the notebook and save it with outputs.

**Comment by SwordSaintLancelot** [comment]
Yes. I will run the notebook and commit along with the outputs as she is editing the notebooks on the VScode web editor.

**Comment by fb0023** [comment]
Thank you @SwordSaintLancelot for all of your help!!! :)

**Review by j08lue — APPROVED** [review]

**Pull request merged**
