### PR TITLE
Fix content

### LINKED ISSUE #2: Customize organization and content of the docs website
# PI Objective
...

# Description
Now that we've set up the website to host the notebooks at https://us-ghg-center.github.io/ghgc-docs/, we need to better organize the content of the website.

See example of veda-docs https://nasa-impact.github.io/veda-docs/, repo here: https://github.com/NASA-IMPACT/veda-docs

# Acceptance Criteria
- [ ] The docs website has relevant content organized in a user-friendly manner

### PR DESCRIPTION
**Pull request by j08lue**
- [x] Convert transformation scripts to notebooks to avoid duplication
- [x] Fix toc
- [x] Remove stub index pages

Closes #2

### CODE REVIEW

**Comment by slesaad** [comment]
Thanks for bringing in the preview @j08lue ! It's awesome!

**Comment by j08lue** [comment]
All notebooks converted. I did rename the files - I think the `_Transformation_Code` postfix is mostly clutter, since the notebooks are in a directory that classifies them. But if we need this postfix, please add it back (to file names and TOC).

**Comment by SwordSaintLancelot** [comment]
I just wanted to mention the names because they have already been updated once and then the excel file was created to keep track of all the names. [This](https://docs.google.com/spreadsheets/d/1tMdM7AVM_Fgk5mwchSW50bH-svpkCGAfFztAPfk1kms/edit#gid=0) excel file has the names that were supposed to be used for all the files. Since I did not decide on any of those conventions, I don't know if removing them or keeping them makes any difference. That's why I suggested either @deborahUAH  or @siddharth0248 might look at them (@Jeanne-le-Roux is on vacation)

**Comment by j08lue** [comment]
Thanks for explaining, @SwordSaintLancelot, I will update the spreadsheet.

How about these, @SwordSaintLancelot - do we need to keep them all and what should their titles be?

```yaml
          - cog_transformation/epa-ch4emission-grid-v2.ipynb
          - cog_transformation/epa-ch4emission-grid-v2express_layers_update.ipynb
          - cog_transformation/epa-ch4emission-grid-v2express.ipynb
          - cog_transformation/epa-ch4emission-monthgrid-v2.ipynb
```

**Comment by SwordSaintLancelot** [comment]
These scripts transform different datasets. Earlier we had to show the annual and monthly dataset but we received the update that we need to transform the express dataset so the three scripts are for those. I am not sure which ones are to be displayed on the dashboard. Then the request was updated again to add new layers which we had to create by combining different variables. So the layers update script is for that. Since it was last minute, I made a new script to create new layers rather than adding the layers in already existing script. I would guess we would like to keep all of these script. But again, @Jeanne-le-Roux is the one communicating about the dataset, I guess she can confirm which datasets to keep.

**Comment by j08lue** [comment]
I'll merge this and keep all four. We can sort out the duplicates subsequently.

**Pull request merged**
